### ISSUE TITLE
installing into current project using npm

### ISSUE THREAD

**Issue by scixor** [creativetimofficial/argon-dashboard-react#16]
I have been trying to install argon in my current project.. which is almost new but has a few things in it.. not in terms of components but in terms of few more packages.
I am using npm for extra info

I have been getting this error:

```FinalizeBuildStatus:
  Deleting file "Release\obj\libsass\libsass.tlog\unsuccessfulbuild".
  Touching "Release\obj\libsass\libsass.tlog\libsass.lastbuildstate".
Done Building Project "C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\src\lib
sass.vcxproj" (default targets).

Project "C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\binding.vcxproj.metap
roj" (2) is building "C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\binding.
vcxproj" (4) on node 1 (default targets).
PrepareForBuild:
  Creating directory "Release\obj\binding\".
  Creating directory "Release\obj\binding\binding.tlog\".
InitializeBuildStatus:
  Creating "Release\obj\binding\binding.tlog\unsuccessfulbuild" because "AlwaysCreate" was speci
  fied.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\H
  ostX64\x64\CL.exe /c /I"C:\Users\STopia\.node-gyp\12.13.1\include\node" /I"C:\Users\STopia\.no
  de-gyp\12.13.1\src" /I"C:\Users\STopia\.node-gyp\12.13.1\deps\openssl\config" /I"C:\Users\STop
  ia\.node-gyp\12.13.1\deps\openssl\openssl\include" /I"C:\Users\STopia\.node-gyp\12.13.1\deps\u
  v\include" /I"C:\Users\STopia\.node-gyp\12.13.1\deps\zlib" /I"C:\Users\STopia\.node-gyp\12.13.
  1\deps\v8\include" /I..\..\nan /I..\src\libsass\include /Z7 /nologo /W3 /WX- /diagnostics:clas
  sic /MP /Ox /Ob2 /Oi /Ot /Oy /D NODE_GYP_MODULE_NAME=binding /D USING_UV_SHARED=1 /D USING_V8_
  SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D V8_DEPRECATION_WARNINGS /D V8_IMMINENT_DEPRECATION_WA
  RNINGS /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0
  /D OPENSSL_NO_PINSHARED /D OPENSSL_THREADS /D BUILDING_NODE_EXTENSION /D _WINDLL /GF /Gm- /MT
  /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\binding\\" /Fd"Re
  lease\obj\binding\vc141.pdb" /Gd /TP /wd4351 /wd4355 /wd4800 /wd4251 /wd4275 /wd4244 /wd4267 /
  FC /errorReport:queue /Zc:threadSafeInit- ..\src\binding.cpp ..\src\create_string.cpp ..\src\c
  ustom_function_bridge.cpp ..\src\custom_importer_bridge.cpp ..\src\sass_context_wrapper.cpp ..
  \src\sass_types\boolean.cpp ..\src\sass_types\color.cpp ..\src\sass_types\error.cpp ..\src\sas
  s_types\factory.cpp ..\src\sass_types\list.cpp ..\src\sass_types\map.cpp ..\src\sass_types\nul
  l.cpp ..\src\sass_types\number.cpp ..\src\sass_types\string.cpp "C:\Users\STopia\Documents\web
  apps\o2\node_modules\node-gyp\src\win_delay_load_hook.cc"
  binding.cpp
  create_string.cpp
  custom_function_bridge.cpp
  custom_importer_bridge.cpp
c:\users\stopia\documents\webapps\o2\node_modules\node-sass\src\create_string.cpp(17): error C26
64: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': cannot convert argument 1
 from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value &' [C:\Users\STopia\Documents\webap
ps\o2\node_modules\node-sass\build\binding.vcxproj]
  c:\users\stopia\documents\webapps\o2\node_modules\node-sass\src\create_string.cpp(17): note: R
  eason: cannot convert from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value'
  c:\users\stopia\documents\webapps\o2\node_modules\node-sass\src\create_string.cpp(17): note: N
  o user-defined-conversion operator available that can perform this conversion, or the operator
   cannot be called
  sass_context_wrapper.cpp
  boolean.cpp
  color.cpp
  error.cpp
  factory.cpp
  list.cpp
  map.cpp
  null.cpp
  number.cpp
  string.cpp
  win_delay_load_hook.cc
Done Building Project "C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\binding
.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\binding
.vcxproj.metaproj" (default targets) -- FAILED.

Done Building Project "C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\binding
.sln" (default targets) -- FAILED.


Build FAILED.

"C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\binding.sln" (default target)
 (1) ->
"C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\binding.vcxproj.metaproj" (de
fault target) (2) ->
"C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\src\libsass.vcxproj" (default
 target) (3) ->
(ClCompile target) -> 
  cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\STopia\Documents\webap
ps\o2\node_modules\node-sass\build\src\libsass.vcxproj]
  cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\STopia\Documents\webap
ps\o2\node_modules\node-sass\build\src\libsass.vcxproj]
  cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\STopia\Documents\webap
ps\o2\node_modules\node-sass\build\src\libsass.vcxproj]
  cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\STopia\Documents\webap
ps\o2\node_modules\node-sass\build\src\libsass.vcxproj]
  cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\STopia\Documents\webap
ps\o2\node_modules\node-sass\build\src\libsass.vcxproj]
  c:\users\stopia\documents\webapps\o2\node_modules\node-sass\src\libsass\src\json.cpp(26): warn
ing C4005: '_CRT_NONSTDC_NO_DEPRECATE': macro redefinition [C:\Users\STopia\Documents\webapps\o2
\node_modules\node-sass\build\src\libsass.vcxproj]
  c:\users\stopia\documents\webapps\o2\node_modules\node-sass\src\libsass\src\sass2scss.cpp(9): 
warning C4005: '_CRT_NONSTDC_NO_DEPRECATE': macro redefinition [C:\Users\STopia\Documents\webapp
s\o2\node_modules\node-sass\build\src\libsass.vcxproj]


"C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\binding.sln" (default target)
 (1) ->
"C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\binding.vcxproj.metaproj" (de
fault target) (2) ->
"C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\src\libsass.vcxproj" (default
 target) (3) ->
  cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\STopia\Documents\webap
ps\o2\node_modules\node-sass\build\src\libsass.vcxproj]


"C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\binding.sln" (default target)
 (1) ->
"C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\binding.vcxproj.metaproj" (de
fault target) (2) ->
"C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass\build\binding.vcxproj" (default tar
get) (4) ->
(ClCompile target) -> 
  c:\users\stopia\documents\webapps\o2\node_modules\node-sass\src\create_string.cpp(17): error C
2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': cannot convert argument
 1 from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value &' [C:\Users\STopia\Documents\web
apps\o2\node_modules\node-sass\build\binding.vcxproj]

    8 Warning(s)
    1 Error(s)

Time Elapsed 00:01:30.69
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\STopia\Documents\webapps\o2\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\STopia\\Documents\\webapps\\o2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\STopia\Documents\webapps\o2\node_modules\node-sass
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev ||
>= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN react-google-maps@9.4.5 requires a peer of @types/googlemaps@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-google-maps@9.4.5 requires a peer of @types/markerclustererplus@^2.1.29 but none is installed. You must install peer dependencies yourself.
npm WARN react-google-maps@9.4.5 requires a peer of @types/react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\argon-dashboard-react\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\STopia\AppData\Roaming\npm-cache\_logs\2019-11-27T04_40_17_029Z-debug.log
```
https://gdl.space/ejudoxoqek.coffeescript the entire log is here ...

I have visual studio 2019 but  I don't know where the problem is... it would be awesome to get some help 😄😅

**Comment by einazare** [comment]
Hello there, @Sid911 ,

Thank you for your interest in working with our products.
At the moment out npm distribution is only for getting our scss/css files. You cannot use it to import js files.
Please check this thread here: https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/50#issuecomment-407030675

Best,
Manu

**Comment by vijaypatidar1** [comment]
![image](https://user-images.githubusercontent.com/76774880/109960482-d61a6400-7d0e-11eb-8993-12617482977e.png)


i got " unexpected token error < "  in build run on browser , I search it everywhere but i couldn't found it.
please help me to solve it.
thank you in advance.

**Comment by einazare** [comment]
Hello there, @vijaypatidar1 ,

Please check these two other issues:
https://github.com/creativetimofficial/argon-dashboard-react/issues/18
https://github.com/creativetimofficial/argon-dashboard-react/issues/3

Best,
Manu

**Comment by vijaypatidar1** [comment]
> ![image](https://user-images.githubusercontent.com/76774880/109960482-d61a6400-7d0e-11eb-8993-12617482977e.png)
> 
> i got " unexpected token error < " in build run on browser , I search it everywhere but i couldn't found it.
> please help me to solve it.
> thank you in advance.

I fixed it by 2 days it's just in pakage.json file there are  i change  "homepage": "https://demos.creative-tim.com/argon-dashboard-react/" into "homepage": "." and it's working thanks to me.
