### ISSUE TITLE
The path argument must be of type string

### ISSUE THREAD

**Issue by peter-palmer** [creativetimofficial/argon-dashboard-react#25]
Hello I just downloaded the project, made "npm i" and "npm start", the project compiles but when I get into google chrome there is an error message that says:

> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (C:\Users\pgarc\Downloads\argon-dashboard-react-master\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\Users\pgarc\Downloads\argon-dashboard-react-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\pgarc\Downloads\argon-dashboard-react-master\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\pgarc\Downloads\argon-dashboard-react-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\pgarc\Downloads\argon-dashboard-react-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\pgarc\Downloads\argon-dashboard-react-master\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (C:\Users\pgarc\Downloads\argon-dashboard-react-master\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (C:\Users\pgarc\Downloads\argon-dashboard-react-master\node_modules\express\lib\router\layer.js:95:5)

I don't know how to solve this and how is getting this error. I'm stuck here. Please help!

**Comment by einazare** [comment]
Duplicate #23 
Also, next time, please follow our rules:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/argon-dashboard-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```

**Comment by zahidayub1122** [comment]
5

I found a fix, seems the problem stems from react-scripts 3.3.x series. In package.json I changed

"react-scripts":"3.3.0" 
to

"react-scripts":"^3.4.0"
then run npm i and ionic serve and it works.

**Comment by quanhieu** [comment]
> 5
> 
> I found a fix, seems the problem stems from react-scripts 3.3.x series. In package.json I changed
> 
> "react-scripts":"3.3.0"
> to
> 
> "react-scripts":"^3.4.0"
> then run npm i and ionic serve and it works.

It working. Thank you

**Comment by srinivasramadas11** [comment]
@zahidayub1122  


this works  now .. thanks for the suggestion

**Comment by shelbyecook** [comment]
OMG THANK YOU
