### ISSUE TITLE
Guide for integration with Gatsby

### ISSUE THREAD

**Issue by nsrCodes** [creativetimofficial/argon-dashboard-react#43]
### What is your enhancement?
If you can provide a few steps on how I can get started with adding the dashboard to an existing gatsby app or using individual components in the basic `gatsby-hello-world-starter`, I would be happy to write the guide for you once I get it setup myself.

**Comment by nsrCodes** [comment]
##### I tried to do it myself but I am getting an error even setting it up. I tried to post the issue here, but maybe some automation kept deleting it so I am mentioning it here as well:
---

### System Details
**OS**:  Pop_OS 19.10 
**Browser**: Firefox 80.0
**App version**: 1.1.0
**Device**: ASUS ROG STRIX II

### Problem
I am trying to get started with using the bundle by following the instruction in the [documentation](https://demos.creative-tim.com/argon-dashboard-react/?_ga=2.128918799.2042698487.1600763687-1720316252.1600763687#/documentation/quick-start)
When I run `npm run install:clean`, I get the following error:

_The app does launch. This message is shown in the browser window_

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at noopServiceWorkerMiddleware (/home/razor/main/Requestly/requestly-work/landingPpage/argon-dashboard-react-master/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/home/razor/main/Requestly/requestly-work/landingPpage/argon-dashboard-react-master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/razor/main/Requestly/requestly-work/landingPpage/argon-dashboard-react-master/node_modules/express/lib/router/index.js:317:13)
    at /home/razor/main/Requestly/requestly-work/landingPpage/argon-dashboard-react-master/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/razor/main/Requestly/requestly-work/landingPpage/argon-dashboard-react-master/node_modules/express/lib/router/index.js:335:12)
    at next (/home/razor/main/Requestly/requestly-work/landingPpage/argon-dashboard-react-master/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/home/razor/main/Requestly/requestly-work/landingPpage/argon-dashboard-react-master/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/home/razor/main/Requestly/requestly-work/landingPpage/argon-dashboard-react-master/node_modules/express/lib/router/layer.js:95:5)
```
----
###### Please let it stay easy to raise issues, whether you attend to them or not is a different thing

**Comment by einazare** [comment]
Hello there, @nsr-py ,

Thank you for your interest in working with our products.
At the moment we haven't worked with GatsbyJS, so we can't give you any guidance on this issue.
I'll leave this issue open for about 30 days, if no one will be able to help you, I am going to close it.

Best,
Manu

**Comment by nsrCodes** [comment]
@EINazare Can you give me guidance regarding my other comment

**Comment by einazare** [comment]
Yes, sorry, I thought it was the from Gatsby, didn't read thoroughly, sorry my bad.
You need to change react-scripts form inside package.json to `3.4.0`. That will solve the issue.

**Comment by nsrCodes** [comment]
Thank you
