### ISSUE TITLE
[Feature Request] Not able to use react lazy() for code splitting

### ISSUE THREAD

**Issue by sameert-iprogrammer** [creativetimofficial/argon-dashboard-react#77]
### What is your enhancement?
We tried using react lazy() for code splitting but after changes, unable to generate build. System hangs if build creation is in progress.
Currently after build we have 4 chunk js files which are having 16mb size hence app takes too much time to load so wanted to split code and improve performance. Please let us know if argon react supports react lazy.
https://react.dev/reference/react/lazy#suspense-for-code-splitting

Version: argon-dashboard-pro-react 1.2.0

Current structure: routes.js file having array of routes and in Admin.js, we have used routes array

**Comment by zhangminGOOD** [comment]
when I run argon-design-system-react  ,there is an error : Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Navbar`.
    at createFiberFromTypeAndProps (react-dom-client.development.js:2510:1)
    at createFiberFromElement (react-dom-client.development.js:2521:1)
    at reconcileChildFibersImpl (react-dom-client.development.js:4613:1)
    at react-dom-client.development.js:4671:1
    at reconcileChildren (react-dom-client.development.js:4933:1)
    at updateFunctionComponent (react-dom-client.development.js:5042:1)
    at beginWork (react-dom-client.development.js:5622:1)
    at runWithFiberInDEV (react-dom-client.development.js:1115:1)
    at performUnitOfWork (react-dom-client.development.js:7695:1)
    at workLoopSync (react-dom-client.development.js:7588:1)      
but I do not change any code , why ? please help me . thank you!
